# Generated by Django 4.0.2 on 2022-02-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('profeta', models.CharField(max_length=30)),
                ('numfieis', models.IntegerField()),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
    ]
